import { createRequire } from 'node:module'
import { readFileSync } from 'node:fs'
import path from 'node:path'

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'

import { RegistryData } from './data.js'
import { GUIDE_TOPICS, VENDOR_DIR, guideTools, newGuideSession, readSkillDoc } from './tools/guide.js'
import { resolveSource, type Source } from './source.js'
import { compositionTools } from './tools/composition.js'
import { discoveryTools } from './tools/discovery.js'
import { imageTools } from './tools/images.js'
import { portabilityTools } from './tools/portability.js'
import { retrievalTools } from './tools/retrieval.js'
import { fail, type ToolDef } from './tools/shared.js'

export const SERVER_NAME = 'html-library'

// Read rather than repeated: the version goes out in the MCP handshake, and a
// hardcoded copy silently disagrees with package.json the first time it is
// bumped. `../package.json` resolves from dist/ in both the workspace and the
// published package, where package.json always ships.
export const SERVER_VERSION: string = createRequire(import.meta.url)('../package.json').version

/**
 * The always-loaded contract. Generated by scripts/build-skill.mjs and vendored
 * in, because the hand-typed version had already drifted — it claimed 55
 * tokenised components when the figure was 54. Read at startup so the counts
 * come from the registry rather than from memory.
 *
 * This is the only channel an MCP client loads automatically, and even then the
 * spec makes it a hint clients MAY add to the system prompt. Depth lives behind
 * get_design_guide; this stays short because clients inject it every session.
 */
const INSTRUCTIONS: string = readFileSync(
  path.join(VENDOR_DIR, 'skill', 'INSTRUCTIONS.md'),
  'utf8',
)
  // Strip the vendoring banner; it is provenance for readers of the repo, not
  // something a client should be handed.
  .replace(/^<!--[\s\S]*?-->\s*/, '')
  .trim()

export function buildServer(source: Source = resolveSource()): McpServer {
  const server = new McpServer(
    { name: SERVER_NAME, version: SERVER_VERSION },
    // `resources` is declared explicitly. registerResource would self-declare
    // it, but only on first call — saying so here keeps the handshake honest
    // about what the server offers regardless of registration order.
    { capabilities: { tools: {}, resources: {} }, instructions: INSTRUCTIONS },
  )

  // The whole skill, readable without a tool call by clients that support
  // resources. Tools remain the path for clients that do not.
  for (const [topic, entry] of Object.entries(GUIDE_TOPICS)) {
    server.registerResource(
      topic,
      `skill://html-library/${topic}`,
      { title: `HTML Library — ${topic}`, description: entry.blurb, mimeType: 'text/markdown' },
      async (uri) => ({
        contents: [{ uri: uri.href, mimeType: 'text/markdown', text: await readSkillDoc(entry.file) }],
      }),
    )
  }

  const data = new RegistryData(source)
  // One session per server, so two servers in one process cannot share it.
  const session = newGuideSession()

  const tools: ToolDef[] = [
    ...guideTools(session),
    ...discoveryTools(data),
    ...retrievalTools(data, session),
    ...portabilityTools(data),
    ...compositionTools(data),
    ...imageTools(data),
  ]

  for (const tool of tools) {
    server.registerTool(tool.name, tool.config as never, (async (args: unknown) => {
      try {
        return await tool.handler(args)
      } catch (error) {
        // A throw here would tear down the stdio session and take every other
        // tool with it, so failures are returned as results instead.
        const message = error instanceof Error ? error.message : String(error)
        return fail(`${tool.name} failed: ${message}`)
      }
    }) as never)
  }

  return server
}

export const TOOL_NAMES = [
  'get_design_guide',
  'get_category_guide',
  'list_components',
  'search_components',
  'get_categories',
  'get_component',
  'get_component_markup',
  'check_portability',
  'get_component_portability',
  'lint_html',
  'recommend_components',
  'get_recipe',
  'get_interactivity_pattern',
  'get_image_prompt',
] as const
